restic-backup-password: ENC[AES256_GCM,data:xAVdjsmxJSCJdexl8A6Tpy0=,iv:IltlS5AJaVbVQug/TAD8QVR0QYsLhRMhTWMQNCaGmg4=,tag:qxBESfc5F+VrEgDqe9M9dA==,type:str]
pihole-webserver-password: ENC[AES256_GCM,data:z/glWfjJfbrBaxJHWYg=,iv:ZSUWhe1XHU6Q2pwGkCof6kgc2RpbORE3wxm6SekMJ+o=,tag:fegG6dX9qyCKoJrvgVhhhQ==,type:str]
wireguard-private-key: ENC[AES256_GCM,data:CpKZrIEyBL/vzD9OFdisdHH2BYX5MrkQ5kyjHNS853oZBv0VqGZbnr9Dlac=,iv:esi3lAbqaxVyi9GFb0/uHX2pAzWr+qptoVuWqvZ19rM=,tag:rziR/Woiv/T/7pv/mc+l+Q==,type:str]
vaultwarden:
    push-installation-id: ENC[AES256_GCM,data:QSxI1DoApIc2X6HTgCkOcBbhA9TTSDunGXbBIJGlpaWeRCle,iv:aKzwPmpFbFaJcy3uPzaFlRXBv1YsIBo4qS6EK2TUd1Y=,tag:TvacOPgesdafGHR5fk5CNA==,type:str]
    push-installation-key: ENC[AES256_GCM,data:/p5ZGV9t39NGXQ9DIVRvZiRMaqU=,iv:uNrbBdVG/nHvkj1uJDLK3H3oHjOZyJGUOCmLR14K9GA=,tag:jSlONJCA7MD9Eh/M5gt2hA==,type:str]
pocket-id-encryption-key: ENC[AES256_GCM,data:ZodeVLB+LB2M/l1/M1XdwQxIlnLXxMo1XETuztSVOTyYQNbrVZgWypgejr/bVJU2uJCP4kerhrd2lUmzILUQ7g==,iv:QM37yGEZeHZrEZb0CKsMNt3CuoC+fupcC9v9eS59N3U=,tag:20UibPJaRpJ/Kkt9b+G9Yg==,type:str]
caddy:
    netlify-access-token: ENC[AES256_GCM,data:mKmadRFCS1CKbxfzN6AA0I1AtIfVf4NS4KWk6N9r+K7MSjwx46FCUg==,iv:vy1Nr+qzMMQuY4RBoArv/lITk04NZXeLpHrhZmiNS/Y=,tag:p+r7FhgqOZ1zzaEY86Y9FA==,type:str]
    pocket-id:
        client-id: ENC[AES256_GCM,data:bmI0wwEJZ9XWQwyLPx+RE3xM5eICPPWo27Cf5Wtx7WLgVas2,iv:KmSD5wE8grQvT+Msn2JvziNVm0JCrAezulx97jdR4oM=,tag:6iy7FF9vITZ1dYLF4unGgQ==,type:str]
        client-secret: ENC[AES256_GCM,data:RMRJ+X5JmxB+eaxPNgSPyGW7/wdDVQ24KwZ17LZe8dE=,iv:OQxLOzTF6+CeKMq+Yh3EOMnVFiVwyuF61HCBQrDGOXk=,tag:8zZiYl8qfaPmtanzpV1sZw==,type:str]
    crowdsec-bouncer:
        api-key: ENC[AES256_GCM,data:UBtSPcPluUjER2UD+ubp7RMiVtza0Y+pgEGes/37jcYAEywbw0otEvXv0w==,iv:T25yMWwzdR/uugH3Amn9DuIuAaQJyXpC3mr+DAqgfZ8=,tag:8KOpFJfEWwCfW6eKD5V0Rg==,type:str]
gluetun:
    wireguard_private_key: ENC[AES256_GCM,data:bx/7+eXI8nE1b4D6LwCU7STGcVRtmSuiKDIYDnKPykDNx8E6kjmRgJVnfuA=,iv:VX/8w+FY0UOxisv95EwFl9g7GyXsvHNDjoocWEC81ug=,tag:LtwVfTs83hzUu/cp2uJhag==,type:str]
    wireguard_public_key: ENC[AES256_GCM,data:gXK5Wcs+OQmSgDj082KDbmgqfc+MJ0T2BgcJHIx3jss7cGOxfWW0Q6YYZ6w=,iv:Vd1EjeEz6kDky/uLRZRKzQUXeJM4i9rdtJmD7gB4uaY=,tag:HdNB3KYR1ZPmrZZbWJGtgA==,type:str]
    wireguard_preshared_key: ENC[AES256_GCM,data:jW18oZw/ZAg5JPuQhTnZuhKwOg5atTUNUmEEB9v2vpmv9iIBYDbg+csJsBA=,iv:ljeQfAEVzO50uh1V/iWAXmmL+HWLUrp9MmjlDUwQtAI=,tag:DxVXb5qmjYJ1P2oouJFY5Q==,type:str]
yamtrack:
    anilist:
        api-id: ENC[AES256_GCM,data:7xRCgms=,iv:1yIVmDGWrkwMHPH6l79ICVNgsytE+5mf+CL/nwMHehM=,tag:KQpNIBUDesOcVL4HPWp8mA==,type:int]
        api-secret: ENC[AES256_GCM,data:94rhxnQPziZ6A940pA4FP/edH8N/wZwu5x6VqokhajCdCg5pDyHPPg==,iv:T5KjTKuGmd5cZACmGHkwJW2lGDwReTaFarL2BGn084Y=,tag:IObWAFHgWewBXFXAQaGMSw==,type:str]
    django:
        secret-key: ENC[AES256_GCM,data:dUn7oeEcLORwO4WZ27w=,iv:tjYsBxBqM/UTOpl1zB6+QIr7/qk6VZj9in6Xuk1gzCE=,tag:w655hRYBnIdPCG6zifLLDQ==,type:str]
    pocket-id:
        client-id: ENC[AES256_GCM,data:voCOwlKnnpFYmaJ6x3MkMwl/6nDYrnBAzjsR1R29VKJqNSmu,iv:94UvlagesSIr4xhZUYyTJ+oAOG2ZaLQtkMcOLEiRH1M=,tag:scAGKuVdsFOa9LjqqrZk+Q==,type:str]
        secret: ENC[AES256_GCM,data:gJiS1sqfhPdrM1RNHRWkvPwo9/Vtyw5ehN8rko1CnqM=,iv:jeZjfRCxeiPoQG13zqCv/28Xrnxp0T44rPYlgURM8IY=,tag:vlVVcJHW6rDlQ2L+8r0LBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz326af7tgfnqpq0l6vk2p78uwp0qn9f5v5exu754rj3t8w0myvqzp4c8e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNN0NPQzRxbHlCMzE1ZW9B
            WlI5YVZ0MWM3THl5d205eGlZdHRJMjhoWURFCk5OWUtvd2VpQ0JqcDVjWnhLOEFD
            Tm9tdzZKd3cvZ1F2WngvcjBraGF1RjQKLS0tIEtsUG9pZC9GN0M2TGNpWHk2djNp
            QnVqa1ZhL2VqZlc2OTZ3T013SU5TYU0KZ1X6A5LZt6XENwciCmEZgfw9HaiKJWvp
            g/PKpRBAcieaR1rpxozdcZjncISFP8h+fRCFucc1neiOom5koBNnUw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18spez0z3wvzw05nhhrka9gmjfvcvhyj7decnw9j4a9xn8m0vyexs0he23r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTVp1MnNna1dQSEswR3cr
            Y0ZiZzlqQ0dVWExQWk9Uay9iSnJnbkE3WjAwClF0eEtiTWxGeUZucG1PNTZaQ3du
            ek5oeFV2SkJVZGtUeXQrQ3pGRUt0UE0KLS0tIGFCbER6emxRZS9uTHJBVEZiZG4z
            YWdodXVZT0ZYQjhVaGR0cDk5L2grSDQKk8QtqORtWk/qhhvrEVg+OYMmsVdaCiCi
            n+ReewCIUA0De57r/lTUnK6pbStmy/3kAiK76KZv1kp4z8j67H3a4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T02:32:08Z"
    mac: ENC[AES256_GCM,data:7ELbwAJUuOrff+A/rO580hHqMWZC47UlHWkYMb4YI4RQt3e+rYgHmoTicpwkUwmhZuunh92aCI0TfvvvJmDqxpOOQDPA/LiE/81R2qjjevv2dqpOTBNOlBQurSjbJsGC29+4rVe78zMFtOEP8bMDk4UQ7YGSzwCQtMjkK/nVPx0=,iv:dHmy1kEcWGxJsjusSIu86rppWh+BGka0Fq3eIREnPIc=,tag:XZCtqIAzTq0Ova9sQ18TNg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
