restic-backup-password: ENC[AES256_GCM,data:HvjJ1hRjE5P6JARZR/+LsiU=,iv:BavVP6OjQ5GUgI7aYSpzUcQcEsoPoQkPB9nwM8USrlM=,tag:9csxENMTnTLBcP3ssn1gyQ==,type:str]
pihole-webserver-password: ENC[AES256_GCM,data:TUkGSQsRTWWuSo+llnc=,iv:CuBPCv61e4H5Xvx2+8hw0iZ/fmcydBTu3VnwS8x1dmY=,tag:B2BolyoZQjeSV1kwVAHOnw==,type:str]
wireguard-private-key: ENC[AES256_GCM,data:7T0uTjNQSPWYp/AlTur2YKkSJF2qXZSqSTumlssKHGB9dVJl1s0bIaMH6GE=,iv:MZAZc1C5Z3Ljjm2bNvPtAaiF/I6h/FmJIcOR893m7/o=,tag:3Ty85y3ud89THqfGTu5bOA==,type:str]
vaultwarden:
    push-installation-id: ENC[AES256_GCM,data:SK1HJax1KvEgYx9mfg0/B1lQhPHFijk82P53V4vGVLbkyoDw,iv:SjdYXlYM8dnz9kwvdEw9ocRzEX/9e2xmuKLPYGJ2tZo=,tag:kdmZd2HcsibYoGZaweaPow==,type:str]
    push-installation-key: ENC[AES256_GCM,data:0RI0U6abIz2IQ9p/VYMFY4G0UX4=,iv:wNshigz7b8AvO9UHNgVR/Nt0vRSmph2q+unic+GEprA=,tag:8UvBqxIO35qK+c4ZB5JJ3g==,type:str]
pocket-id-encryption-key: ENC[AES256_GCM,data:9G56zyl+JIXPtwlbrPXEGbrZJCY/MTqPSpEv2xc+p4W8NZDxQct86LMfTYtvXnlfDxIn82yLnO2N/mc4fuWl0g==,iv:VCCDC1nC5Iy58Y5owiAVT0vtYlyHH8Qunb7GdME3QmY=,tag:3mUZigeO50tBjcfKaH2QVA==,type:str]
caddy:
    netlify-access-token: ENC[AES256_GCM,data:+HVk2k3bxrrPp0V25xp1FzcsKotlFw+pqXO8P4NKuCZQxT47YP/dCg==,iv:4K/cIAr6jwT9aYEUvxYn5F7+oAJ4Q2VP/UWUGpMe2ZA=,tag:zyLYpErNfAW3Pbl9S9SYmg==,type:str]
    pocket-id:
        client-id: ENC[AES256_GCM,data:zTRKqKivUE4z4cp9RzlJF9Az9ij30BBu36S52Vy1NG3EFGeN,iv:/NLj4LGzqKYieJjWkklTMw/M5K0b79BN+BzcLvqEpa4=,tag:1S6JZKJHZ2OGW0qhvbU0/w==,type:str]
        client-secret: ENC[AES256_GCM,data:R1CryclviTmaMl0UJwJIwKLWySZUQfVqW+x6A92zXXU=,iv:4A30DotxaeEhBPG03bZPAghMiQ3TZioe0zROHnKy5Mc=,tag:7PmIqts/dSZixWagBbm7Tw==,type:str]
    crowdsec-bouncer:
        api-key: ENC[AES256_GCM,data:d1V5EbqtnjeA1YIaTG3jTUe3RlOrtzC41rZVYWkDLzXj+v2kNIcTVDAIhg==,iv:S9CX19Dt/lxF3cwYsHRbqosN/dO/jAMjTPjgebTYg/s=,tag:gBT8rilqprRVQ6sC+LCYuw==,type:str]
gluetun:
    wireguard_private_key: ENC[AES256_GCM,data:rVWZRCJJo5G++iwDaXXkAeOPNOHUQlc+s7vQePrNnmyBoJIo8rlaeq+m2wM=,iv:xapltbKCH34DHLhqS2d+Hz/b6yn2WGWgActrtApvw0k=,tag:3w9Vhjb49cQkpuSuCeJPQw==,type:str]
    wireguard_public_key: ENC[AES256_GCM,data:3MDYcoGTe2eabF0xdoj3ozECwXC1KzTBxbtdnpCplbUDgQ2dhPLoF8Imu2w=,iv:ga/OxgHJyVNPw3A+O4n08DYW8ckc0RQUgh+qyPkt2yA=,tag:YO7PQCk2R9XvrIFpFJjo+Q==,type:str]
    wireguard_preshared_key: ENC[AES256_GCM,data:4WwlgYKRYbc3vjmVl/dV91p1e+U5VddxT9b19SSAuLZGrMIMAojuHXu+J/s=,iv:edH9xDIUH3duGneOgglQn7RCed9Mq03iIHjvbDBO9+g=,tag:vJIp/wGPSDBlVeBt+PtJhw==,type:str]
yamtrack:
    anilist:
        api-id: ENC[AES256_GCM,data:SLHplRI=,iv:W6wfcKzxQS5S1/D7+Jt5bvZY29MOQAClIirf0+Ckfeo=,tag:NjjYewdS1Vdv3fNndROgIQ==,type:int]
        api-secret: ENC[AES256_GCM,data:ZAK+nBExsEm4P1e1dlooFhTMwMsYLEjUp4qJiGJjJPi2w/+dOuuq5g==,iv:yOmaodIRzIU1RBD9ny34HACYmlrhKSOlLCrjFA/5Puw=,tag:kF2UNHefIvyPCvrmRfDR7w==,type:str]
    django:
        secret-key: ENC[AES256_GCM,data:6S15pCPI4y2QHlFd4qg=,iv:oH7FyTp5ppQXr5J7mH0my6VNTUOHvotYD3evHe06RXU=,tag:aCtpf8BHITKR48dTVu4FpA==,type:str]
    pocket-id:
        client-id: ENC[AES256_GCM,data:SlWsF1N1Xwy6m1OvQmCcjcu2WWYNIcCF4rZKp0/pBtKd3XP5,iv:b3nUF3qvT9biKk6mcWOa/RNfPzZQJ9sxaMQo0jUL42w=,tag:ujGPnnkEaQxuEeW5s+D3cQ==,type:str]
        secret: ENC[AES256_GCM,data:yONEe6g2N1M5lRc2Tjuq/cmGoF00cr6tu2h6tGBx72E=,iv:VUfNDcs9oD5Zlrrsq+tTw0DqN9rWzJPTa7onhA+nwJg=,tag:Fa1ZEJ4MAEQBSsHOwOglNA==,type:str]
    steam-api-key: ENC[AES256_GCM,data:stbMApj0yPFV1DIDax0mTIH2xmwR+4wmxcq6+plIwQ8=,iv:pAc9bcBGrnB9imGAGl1fLLmAXxJMYmwfKMvHiQcMP4w=,tag:FkF1nCg9+Wd9/rOJH/In7Q==,type:str]
slskd:
    web:
        username: ENC[AES256_GCM,data:6P0JyANq/Yy00mMyLw==,iv:jM3IDpsEjzkPfBcbRghg2guO5xp8JHRqlH7R2h9XwhY=,tag:jSLO2hk2/I2ytMvdadU7lw==,type:str]
        password: ENC[AES256_GCM,data:5JcrnRFoxxWjeXhRFgw=,iv:wq2sL26cSSJlOywCIwvSr1OV4BseHbJy8g1Les5Gx9U=,tag:3A72vJb8N9Y+QNMUzsd8pQ==,type:str]
    api-key: ENC[AES256_GCM,data:8vIU7gzxpWkpT+gLolqRbsL+18YQinJs0kTYsck0O/4=,iv:Ruw1UxBQmGucv5H2fF4OX6e7naKtGo15GJHOlb3esW4=,tag:6d2I5FDhvsMx8JPofLgCAA==,type:str]
    soulseek:
        username: ENC[AES256_GCM,data:Q4177FudOCZ+5VKD,iv:2ZRKrlJyDBkBVWoC9XTPglNWDYqxGxjLMw+G2Hz66Ag=,tag:zSaQi71a+JIoBp/GirbilA==,type:str]
        password: ENC[AES256_GCM,data:dQce5XhfzOWCCxeBAsI=,iv:PvHr/TFjvGR45wqijBAwz7VdUwQACun1l1ooT3zci8U=,tag:N5FxdEeR6IiwUcE7UJzxwQ==,type:str]
wrtag:
    web-api-key: ENC[AES256_GCM,data:seQiPJnFw3YafD0EQ/56EGECrEc04pbTNfCQ2v5xRQI=,iv:g09YdK+S25z92FxeFS1b0OQwxycvsiLUljK+yWoW+H0=,tag:dIl+Nak5CrOQ/te3F6y2QQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz326af7tgfnqpq0l6vk2p78uwp0qn9f5v5exu754rj3t8w0myvqzp4c8e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUXB2L0pDMlI1QkQ4bWxU
            cjhCSlg3bHVxcFNMY21mZ0hwTVc0Wk0vREg0Cm5wSnc3QUVKdVVBR2dkdTlUaEtt
            THlwUWNVVzkySEgzdnQ4MHE0OHhQY28KLS0tIHFVdE1HbUREdXVCazZ2eG5KdnUw
            eGZkY3lXUytlVVp5S0VvZGY0U1IxSnMKqJbg/CamG/mzQTDxKAm3uwOt7v/pOe6L
            5kEsHyZAqlaBmAYPCPHELMQiQdIsFdzimvGFqonIHzXBGNtSbRE2Mg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18spez0z3wvzw05nhhrka9gmjfvcvhyj7decnw9j4a9xn8m0vyexs0he23r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOWhUa29ETzI1U0hDM0Vz
            S2tXeFA4NlpDVkJRRUZzUVZYQVdPZmUyYXdJCno5cVJ3ekZiRm1oRDRNcm9yVlZ5
            Q00wS3ljZklLdUU3Q25OT25ZTklGcFkKLS0tIDN0dnEvWUFOb3cwR25Sd2M0bEtl
            WE9BOVBldy91SjEyUWpaWHFiV0J2N0UKKLaWJoCZdEFhYebUH4AuSh5Qv/931OCq
            RzjDKirOaxb+7F5D94HcGDN5AJVqW0K2rwFCRGIYz1ghVbDcKx5twg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T07:59:03Z"
    mac: ENC[AES256_GCM,data:J0qf+HVIbxpXtui/87nQNbDjCzE9bnPt3/k8KWicp+U2IjzU4p4Twd1bkuyigqa/+8t2BIEqsUQc4WudVXctp83kIMEE39wk0h6YahC3+nfCOy6mbMchn/gkvVA+2IvObfXRqsmhZPj+LsjK8g3KmMAHKKRdpUn2IFWpowEOt7o=,iv:cuj70Z7T1oUkTFO4xC9FDthUgtH09eyKiIeOwrdwnjc=,tag:v3qMYIfeUNnbUmhEOrmjuA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
