restic-backup-password: ENC[AES256_GCM,data:ehcUm21Z2KtWuhJPKuRQ7BY=,iv:vysdrDJz9c0dVY3awekWoVnrbN05x0cRWVIE+8RNBi8=,tag:FzhtfZqj6J0PNvP3jiv8Wg==,type:str]
pihole-webserver-password: ENC[AES256_GCM,data:St3as3Sp7amtQbSO8cQ=,iv:v/4eSPjUJpmI9YsJHKazJL4Vtj0RSSZ1IayqZUGZTpE=,tag:fpJsal/V5f8SQ1+rc8JdpQ==,type:str]
wireguard-private-key: ENC[AES256_GCM,data:2npy4iP6Vx40VDIAvcFhMvAbRCtHoKoB3IGb32RIPZZH9TeeMbrdjWnFIv8=,iv:1e6Le9Tkn+jCaxZy2ZYegrUl9UgMeW0MT4CqGvq2GBk=,tag:7p4amB8w+WBtZaE+GN+CAQ==,type:str]
vaultwarden:
    push-installation-id: ENC[AES256_GCM,data:5RPMv7lUBxiVwErOLBDz2n5UkAQO/I0uYPDnBkq2YcaART8f,iv:C8m7y1F10A8tt3y39l3g+Okg9PTG4aF05l77JQzftjU=,tag:RiqQmaY4YScOUP1LVlpHFA==,type:str]
    push-installation-key: ENC[AES256_GCM,data:Sz7AuHdbbEZ5AsUmMtUNnUeCymk=,iv:m0GjpPAE6Fvh9BwGVN9W8/fjpItvR32Urp/kM0jL488=,tag:Ao40467PyTwhVXSjgYIvqQ==,type:str]
pocket-id-encryption-key: ENC[AES256_GCM,data:9B1oQQ+EHd31yaqmErcCcVhMLQ76LTnEoZY1Rlu7k0W0a4HnvEkgYRdyV2v8rnQdLaJTu2xrnNG+O4F3brJ2mg==,iv:Gz0yEYXBTlDHs3AI8cbm3EH6Pon2eODP+IGjvRteD38=,tag:fjmk8cV2qvUlCkgZE+dcUA==,type:str]
caddy:
    netlify-access-token: ENC[AES256_GCM,data:rPa4uPrPdXbZvdwOybxsPEyyKn1ok1HkKqz0Y4XuoljDFws83PeNqg==,iv:9yl6mpBoPoV+xf1lBtt/kHr5DRbOhCeisyEHuLVsaIw=,tag:9b0IfLf42QorvJeWxOsPGQ==,type:str]
    pocket-id:
        client-id: ENC[AES256_GCM,data:xUtiI13OZQHe/LvwU+j8rye2oS9zoj8FA3Guh5lgNh0Oix99,iv:L724isPQ7LGbyOKNQas8lHWvkE+U0RrG3Ndq4CqjeJs=,tag:LEfAtZN7QPw6Fqi/IKZtkg==,type:str]
        client-secret: ENC[AES256_GCM,data:/59ie6nTe3XjwhsI7t7fXPdXGh86i+wdVkLLVbWI1RU=,iv:WfFUqnvQFLXkTddvHO2gaY9VWGsvyDdcGZS31WhT7pc=,tag:dw7VuuQ90uj2RWdyqtPUWQ==,type:str]
    crowdsec-bouncer:
        api-key: ENC[AES256_GCM,data:uav3t8OMGV50eFUxzQ1YTixg4xlJhWpSNpB7In+nFLx/hfoi5TIEg3sRaw==,iv:6YHj5f2cA17/hHFdWJXSOuneHcN+rzcl8llt9dORDQs=,tag:YAlZ2K7io39X6iNycOhyXQ==,type:str]
gluetun:
    wireguard_private_key: ENC[AES256_GCM,data:unUaCvjWF3KSjvnMQOq7wDpu/uQfsP+vMxUVnMOZiuSoThUy0/I+F5NYzIk=,iv:2nXxBQcFhfMfEG0v6JYEmUQMhShcUWIM46HMC2/mcfM=,tag:DBgPqdtzbWEepQ/XaZm+Jg==,type:str]
    wireguard_public_key: ENC[AES256_GCM,data:+s0uEnTzurGqr0rLZ6yqXLhWa/6vrXbXph+mvBpK1ceYCLCnwgtPbRlKpeQ=,iv:01X5/ak3XYh9S16KK5HXCchyWQao8RA+ICxSoLAXOnc=,tag:L/UGRsypoqu+eBI/A8omkA==,type:str]
    wireguard_preshared_key: ENC[AES256_GCM,data:8RuZrcO1TYukIItMOOaYEtehNXm8CaWtkMzkGON4hTNj7NzcRUJ04uKg7Do=,iv:9272cMO4SPjlHElEgtJPwdB8GAt95LjoCjAACySCtT8=,tag:fw0M9c1osUJwzT8fNe0Ykg==,type:str]
yamtrack:
    anilist:
        api-id: ENC[AES256_GCM,data:MNMFDG4=,iv:aVk1cA27hpR5Gu8aPN2J5T132/9yHzKae/9ftFFABSY=,tag:FqJKK6thdKLvw9U8vgPNng==,type:int]
        api-secret: ENC[AES256_GCM,data:vrVEQhM6E9oJ44Pm6xIM/y73qDkFgCO8CikVIDJqDVFHJyXVUAHzQg==,iv:aqo4hDebQMCB0j6Caj1N06mvtbfz8IJptGBTVZwnYC8=,tag:fGEEcti62k1rHQJFx1DCsw==,type:str]
    django:
        secret-key: ENC[AES256_GCM,data:7NzkFNw7da2wgxeckcI=,iv:Gb6K5os4OkCtwt7aELvMF8lC+0Mpae5xEA8syrIOcng=,tag:5hiLI+BphAoov7eYqCgCGw==,type:str]
    pocket-id:
        client-id: ENC[AES256_GCM,data:BHpvrOQGTyDi3nTbaa4BlnjZI0cBuPiKCquXEQAzS4b5ma/s,iv:af27EuR37Tit2ThvYyaSelPh3LAeSc0y6jGisAE1edQ=,tag:8YST2VLSx1/5XSffSNZMgg==,type:str]
        secret: ENC[AES256_GCM,data:eh12+6pnmjUO7VVQ/yZ3ednxEfvxSx0plewuOG/Dm7k=,iv:6hZTBz7KTVeMVwhLbxXQPUlgKAnGX7p9T2IR85Cngro=,tag:MvwcBapUeq2kS/pSClU0mQ==,type:str]
    steam-api-key: ENC[AES256_GCM,data:grDi9QTc/LFeSqgy342Ftz5OisqMQSSGMj9RkFmJykU=,iv:B6wblOz5JXz4iId7Jg9a4HYltV3vCWl269IcezzogrE=,tag:NBNEi0bW9FPI4Gg0ieTRKw==,type:str]
slskd:
    web:
        username: ENC[AES256_GCM,data:5k9LXm6uWLlwfo85Pg==,iv:64TUd39aMuvB7Podl8MslWC19tTJmQDoI9PxU8KtdkI=,tag:HiY5ScP9WzXneOF2N1wMaA==,type:str]
        password: ENC[AES256_GCM,data:aQP2lQc4i/v6fRHnoYw=,iv:V43W2t9C5IkG1umlwnO89GLMaczZTJAX5ecukNuiHSY=,tag:iHRM565u52UA6Rnmud0HOw==,type:str]
    api-key: ENC[AES256_GCM,data:0OjdUOMGb2fU3PVvjj4cHaz287fl0M106NmqA4pwDMw=,iv:NXdzTqM90kvzdijTsjp6vAvZJBFexP457LVu/X6a47s=,tag:/QYT5BQGKDy52hsvyfTY6w==,type:str]
    soulseek:
        username: ENC[AES256_GCM,data:uxrx9AEL2AiakhiD,iv:SP1pME4wsoaC0Re+T9tTNY5u0qce9l02wQfKEasZFZI=,tag:rzT7hs+GHT3qb4E8PM/LEg==,type:str]
        password: ENC[AES256_GCM,data:O2N+R/O18R4kbOjSgpQ=,iv:k268B2CSVEX6C9yYIs9cOD0fgY4gIJDmubH3OWjtyOo=,tag:3yM+Xm9H8wy8mC49IpeSJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz326af7tgfnqpq0l6vk2p78uwp0qn9f5v5exu754rj3t8w0myvqzp4c8e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRGw3RnZKVUg3NGpFVkRT
            VWVLUWplWlVOaTlla2o3MU11aGh2ZVgrOG04CjRXSWZJQ3ZjWi8vd25hMUdqa1lJ
            OXp1UnVnOThKdVNUMzFjTnZFRUhnN3cKLS0tIERoRGZTOGRKMFc1ZklDM0pkV3Nl
            TGl6eS90eW1aUzBFQ2hsTDB6TURvcjQKEkauskGHoOfE51xsuExtRMkoiTPEEuXV
            JoVC4xVAcjg7C1h0/CFVNRSC17nccg0vuxeEHz83YgE9gu6id78B5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18spez0z3wvzw05nhhrka9gmjfvcvhyj7decnw9j4a9xn8m0vyexs0he23r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpT2pOc1ZRd3gyckF0YzBT
            clRRd2ZFeVVBNkdpMURVaWU0eHhVMkZrb0Q0Cm1tRWdrTGxndHZEaGU1VmdWdldt
            S0hlemk4TmNhMEk4TVdHMzdxb3Z5d0UKLS0tIEJxTHFFZ0pCdGVnS1I1K3VDZlVT
            R21jTDBKd1kvM1VLS0JKNkdiVzIrRFUKkLDFrV0JPfym7l+cDN7UW8KJsGrB/fHA
            AHotLP0/8uKcum9AU3sG5+2VkKmaMi+3oDGWhzYYdDyTV3MWOV5J+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T06:16:39Z"
    mac: ENC[AES256_GCM,data:OwRxD5TSg0Edej+LwQqk+ymwGbYlshF6eZbD4/EKn9llv+lkAltosXkPQIsQb9EwUg1xBQzXk1kCJFYtdbXEH+ftMptidTfMf71pe3UaPiicZTqdshdAZDAB8FP1vegbKacIdpsZ0jT3yXZXJ6aNV5rOWSivglkKTKE/uPfvQXU=,iv:lWLmNEiwG151pCgRNJlNm0PTO0I9HvixYSVkbbjxp3E=,tag:2+N4s+rjClW28522mCsQCA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
