#!/bin/sh

# post-new --- Notmuch rules that run after notmuch new

# * Mailing lists
# Everything for the mailing lists I’ve subscribed to with my personal
# emails or that I pull in locally using lore 2 maildir (l2md).  For
# clarity, I give each mailing list at least its own line, rather than
# grouping common tag operations into a single notmuch query.  We we
# trade clarity for potential succinctness.
notmuch tag +list +emacs -- 'List:"<emacs-devel.gnu.org>"'
notmuch tag +list +emacs -- 'List:"<help-gnu-emacs@gnu.org>"'
notmuch tag +list +emacs -- 'List:"<emacs-tangents@gnu.org>"'
notmuch tag +list +emacs -- 'List:"<bug-gnu-emacs.gnu.org>"'
notmuch tag +list +emacs -- 'List:"<emacs-orgmode@gnu.org>"'
notmuch tag +list +emacs +humanities -- 'List:"<emacs-humanities@gnu.org>"'
notmuch tag +list -- "path:l2md/**"
notmuch tag +list +guix -- "path:/^l2md\/guix-[^/]+\/.*/"
notmuch tag +list +guix +mumi -- "path:l2md/mumi-bugs/**"

# * Newsletters/subscriptions
notmuch tag +sub -- from:@substack # Any substack
notmuch tag +list +humanities +writing -- from:amugofinsights@substack.com
notmuch tag +sub +writing -- from:poem-a-day@poets.org
notmuch tag +sub +news -- from:nytdirect@nytimes.com
notmuch tag +sub -- from:early-modern-world@brown.edu
notmuch tag +sub -- from:"Aeon+Psyche Daily"
notmuch tag +sub +news -- from:"News from Brown"
notmuch tag +sub -- from:newsletter@thebaffler.com
notmuch tag +sub +news -- from:email@washingtonpost.com
notmuch tag +sub +job_search -- from:jobs-noreply@linkedin.com
notmuch tag +sub -- from:messages-noreply@linkedin.com
notmuch tag +sub +humanities -- from:humanities-institute@messages.brown.edu
notmuch tag +sub +job_search -- from:handshake@notifications.joinhandshake.com
notmuch tag +sub -- from:crc@messages.brown.edu
notmuch tag +sub +news -- from:herald@browndailyherald.com
notmuch tag +sub -- from:video@mailer.e-flux.com
notmuch tag +sub +buoy -- from:buoyinspirations@64429489.mailchimpapp.com
notmuch tag +sub +productivity -- from:@flourishedhope.com
notmuch tag +sub +writing -- from:thehighpony@buttondown.email
notmuch tag +sub +conspire_creative -- from:"The Profitable Author from Conspire Creative" or subject:"Your ABC Nudge, vol."
notmuch tag +sub +crc -- from:"Brown University Curricular Resource Center"
notmuch tag +sub +productivity -- from:dinigroup@kouroshdini.com

# * Parents’ condo
notmuch tag +condo -- from:"Belmont Row HOA"

# * Job search
notmuch tag +job_search +sub -- from:jobs-listings@linkedin.com

# * Parents
notmuch tag +parents -- 'from:christine.balintona@ascension.org or to:christine.balintona@ascension.org'
notmuch tag +parents -- 'from:christine.balintona@gmail.com or to:christine.balintona@gmail.com'
notmuch tag +parents -- 'from:CBalintona@presencehealth.org or to:CBalintona@presencehealth.org'
notmuch tag +parents -- 'from:reyes.jason@gmail.com or to:reyes.jason@gmail.com'

# * Updates
notmuch tag +update -- from:"no.reply.alerts@chase.com"
notmuch tag +update -- from:noreply@redditmail.com

# * Spam
# Generally I should take care of my inbox by unsubscribing from lists
# I do not like.  But below are the exceptions.
notmuch tag -inbox +spam +trash +sub -- 'from:jesse_polhemus@brown.edu' # Sender of CS department mailing lists
notmuch tag -inbox +spam +trash +sub -- 'from:dsi@browndatascience.ccsend.com'

# * Machine-local

# ** Sent
# Sending from Gmail doesn't add the "sent" tag, so we manually add
# it.
notmuch tag +sent -- "(from:kristoffer_balintona@brown.edu or from:krisbalintona@gmail.com or from:kristoffer_balintona@alumni.brown.edu) and not path:drafts/**"

# ** Email drafts
notmuch tag +draft -inbox -unread -- 'path:drafts/**'
# Mark local email drafts that are more than 1 month old for deletion.
# See pre-new hook for how I delete these files.
notmuch tag +delete -- 'path:drafts/** and date:..1month'
