#!/bin/sh

# post-new --- Notmuch rules that run after notmuch new

# * Process "new" tags
# Instead of adding the inbox and unread tags to all emails (via the
# notmuch new.tags setting), I add the "new" tag.  This is to allow
# all emails synced by lieer to be untouched (the inbox and unread
# tags are not added to them); we simply remove the new tag from these
# emails.  For non-lieer-managed emails, we add the inbox and unread
# tags.  This approach means we don't have any unexpected behaviors
# with lieer's syncing of gmail labels.
notmuch tag -new -- 'tag:new and (folder:/personal/ or folder:/uni/ or folder:/drafts/)'
notmuch tag -new +inbox +unread -- 'tag:new and not (folder:/personal/ or folder:/uni/ or folder:/drafts/)'

# * Mailing lists
# Everything for the mailing lists I’ve subscribed to with my personal
# emails or that I pull in locally using lore 2 maildir (l2md).  For
# clarity, I give each mailing list at least its own line, rather than
# grouping common tag operations into a single notmuch query.  We we
# trade clarity for potential succinctness.
notmuch tag +list +emacs -- 'List:"<emacs-devel.gnu.org>" or to:"<emacs-devel.gnu.org>"'
notmuch tag +list +emacs -- 'List:"<help-gnu-emacs@gnu.org>" or to:"help-gnu-emacs@gnu.org"'
notmuch tag +list +emacs -- 'List:"<emacs-tangents@gnu.org>" or to:"emacs-tangents@gnu.org"'
notmuch tag +list +emacs -- 'List:"<bug-gnu-emacs.gnu.org>" or to:"bug-gnu-emacs.gnu.org"'
notmuch tag +list +emacs -- 'List:"<emacs-orgmode@gnu.org>" or to:"emacs-orgmode@gnu.org"'
notmuch tag +list +emacs +humanities -- 'List:"<emacs-humanities@gnu.org>" or to:"emacs-humanities@gnu.org"'
notmuch tag +list -- "path:l2md/**"
notmuch tag +list +guix -- "path:/^l2md\/guix-[^/]+\/.*/"
notmuch tag +list +guix +mumi -- "path:l2md/mumi-bugs/**"
notmuch tag +list +guix +emacs -- '"List:<~abcdw/rde-discuss.lists.sr.ht>" or to:"~abcdw/rde-discuss.lists.sr.ht"'

# * Newsletters/subscriptions
notmuch tag +sub -- from:@substack # Any substack
notmuch tag +list +humanities +writing -- from:"amugofinsights@substack.com" or from:"a-mug-of-insights@ghost.io"
notmuch tag +sub +writing -- from:poem-a-day@poets.org
notmuch tag +sub +news -- from:nytdirect@nytimes.com
notmuch tag +sub -- from:early-modern-world@brown.edu
notmuch tag +sub -- from:"Aeon+Psyche Daily"
notmuch tag +sub +news -- from:"News from Brown"
notmuch tag +sub -- from:newsletter@thebaffler.com
notmuch tag +sub +news -- from:email@washingtonpost.com
notmuch tag +sub +job_search -- from:jobs-noreply@linkedin.com
notmuch tag +sub -- from:messages-noreply@linkedin.com
notmuch tag +sub +humanities -- from:humanities-institute@messages.brown.edu
notmuch tag +sub +job_search -- from:handshake@notifications.joinhandshake.com
notmuch tag +sub -- from:crc@messages.brown.edu
notmuch tag +sub +news +brown -- from:herald@browndailyherald.com
notmuch tag +sub +brown -- from:brown-fund@brown.edu
notmuch tag +sub -- from:video@mailer.e-flux.com
notmuch tag +sub +buoy -- from:buoyinspirations@64429489.mailchimpapp.com
notmuch tag +sub +productivity -- from:@flourishedhope.com
notmuch tag +sub +writing -- from:thehighpony@buttondown.email
notmuch tag +sub +conspire_creative -- from:"The Profitable Author from Conspire Creative" or subject:"Your ABC Nudge, vol."
notmuch tag +sub +crc -- from:"Brown University Curricular Resource Center"
notmuch tag +sub +productivity -- from:dinigroup@kouroshdini.com
notmuch tag +sub -- from:"Medium Daily Digest <noreply@medium.com>"
notmuch tag +sub -- from:"Diane Callahan <subscriptions@medium.com>"
notmuch tag +sub +philosophy -- from:"Joan Westenberg <subscriptions@medium.com>"

# * Parents’ condo
notmuch tag +condo -- from:"Belmont Row HOA"

# * Job search
notmuch tag +job_search +sub -- from:"Indeed <donotreply@match.indeed.com>"
notmuch tag +job_search +sub -- from:jobs-listings@linkedin.com
notmuch tag +job_search +sub -- from:alert@email.nexxt.com
notmuch tag +job_search +sub -- from:"Nexxt <TopJob@email.nexxt.com>"

# * Parents
notmuch tag +parents -- 'from:christine.balintona@ascension.org or to:christine.balintona@ascension.org'
notmuch tag +parents -- 'from:bebetyn@gmail.com or to:bebetyn@gmail.com'
notmuch tag +parents -- 'from:christine.balintona@gmail.com or to:christine.balintona@gmail.com'
notmuch tag +parents -- 'from:CBalintona@presencehealth.org or to:CBalintona@presencehealth.org'
notmuch tag +parents -- 'from:reyes.jason@gmail.com or to:reyes.jason@gmail.com'

# * Updates
notmuch tag +update -- from:"no.reply.alerts@chase.com"
notmuch tag +update -- from:noreply@redditmail.com
notmuch tag +update -- from:notifications@github.com

# * Spam
notmuch tag -spam -- tag:emacs
# Generally I should take care of my inbox by unsubscribing from lists
# I do not like.  But below are the exceptions.
notmuch tag -inbox +spam +trash +sub -- 'from:jesse_polhemus@brown.edu' # Sender of CS department mailing lists
notmuch tag -inbox +spam +trash +sub -- 'from:dsi@browndatascience.ccsend.com'

# * Machine-local

# ** Sent
# Sending from Gmail doesn't add the "sent" tag, so we manually add
# it.
notmuch tag +sent -- "(from:kristoffer_balintona@brown.edu or from:krisbalintona@gmail.com or from:kristoffer_balintona@alumni.brown.edu) and not path:drafts/**"

# ** Email drafts and sent
notmuch tag +draft -inbox -unread -- 'path:drafts/**'
notmuch tag -inbox -unread -- 'tag:sent'
# Mark local email drafts that are more than 1 month old for deletion.
# See pre-new hook for how I delete these files.
notmuch tag +delete -- 'path:drafts/** and date:..1month'
